import type { Locale } from "../../i18n";
import type { MaterialId } from "./types";

const materialNames: Record<Locale, Record<MaterialId, string>> = {
  ja: {
    "material-001": "首元のゆるいTシャツ",
    "material-002": "ゴム紐ショートパンツ",
    "material-003": "硬いバゲット",
    "material-004": "古びたマント",
    "material-005": "赤い布ベルト",
    "material-006": "小さな水鉄砲",
    "material-007": "平凡な部屋着",
    "material-008": "急ごしらえの尖り帽子",
    "material-009": "赤い鉛筆",
    "material-010": "赤いスカート",
    "material-011": "リサイクル紙袋",
    "material-012": "おもちゃのナックル",
    "material-013": "赤いエプロン",
    "material-014": "古びた眼鏡",
    "material-015": "エナジードリンク",
    "material-016": "ボクシンググローブ",
    "material-017": "小さな仮面",
    "material-018": "小さなパン切りナイフ",
    "material-019": "水泳ゴーグル",
    "material-020": "古いスプーン",
    "material-021": "平凡なスリッパ",
    "material-022": "投石パチンコ",
    "material-023": "古びたスリッパ",
    "material-024": "壊れた傘",
    "material-025": "キャンディリング",
    "material-026": "赤い首掛け浮き輪",
    "material-027": "細糸の指輪",
    "material-028": "古びたリストバンド",
    "material-029": "細糸のブレスレット",
    "material-030": "古びた櫛",
    "material-031": "渦巻きキャンディネックレス",
    "material-032": "古びたコップ",
    "material-033": "冷感ネックカバー",
    "material-034": "古びた小銭入れ",
    "material-035": "キャンディイヤリング",
    "material-036": "物理武器の設計図（2段階）",
    "material-037": "靴の設計図（2段階）",
    "material-038": "魔法武器の設計図（2段階）",
    "material-039": "きらめく装飾品の設計図（2段階）",
    "material-040": "鎧の設計図（2段階）",
    "material-041": "鮮やかな装飾品の設計図（2段階）",
    "material-042": "帽子の設計図（2段階）",
    "material-043": "物理武器の設計図（3段階）",
    "material-044": "魔法武器の設計図（3段階）",
    "material-045": "鎧の設計図（3段階）",
    "material-046": "帽子の設計図（3段階）",
    "material-047": "靴の設計図（3段階）",
    "material-048": "きらめく装飾品の設計図（3段階）",
    "material-049": "鮮やかな装飾品の設計図（3段階）",
    "material-050": "物理武器の欠片（4段階）",
    "material-051": "魔法武器の欠片（4段階）",
    "material-052": "鎧の欠片（4段階）",
    "material-053": "帽子の欠片（4段階）",
    "material-054": "靴の欠片（4段階）",
    "material-055": "きらめく装飾品の欠片（4段階）",
    "material-056": "鮮やかな装飾品の欠片（4段階）",
    "material-057": "物理武器の設計図（5段階）",
    "material-058": "鮮やかな装飾品の設計図（5段階）",
    "material-059": "魔法武器の設計図（5段階）",
    "material-060": "鎧の設計図（5段階）",
    "material-061": "帽子の設計図（5段階）",
    "material-062": "靴の設計図（5段階）",
    "material-063": "きらめく装飾品の設計図（5段階）",
    "material-064": "物理武器の設計図（6段階）",
    "material-065": "鮮やかな装飾品の欠片設計図（6段階）",
    "material-066": "魔法武器の設計図（6段階）",
    "material-067": "鎧の設計図（6段階）",
    "material-068": "帽子の設計図（6段階）",
    "material-069": "靴の設計図（6段階）",
    "material-070": "きらめく装飾品の欠片設計図（6段階）",
    "material-071": "物理武器の欠片（7段階）",
    "material-072": "魔法武器の欠片（7段階）",
    "material-073": "鎧の欠片（7段階）",
    "material-074": "帽子の欠片（7段階）",
    "material-075": "靴の欠片（7段階）",
    "material-076": "きらめく装飾品の欠片（7段階）",
    "material-077": "鮮やかな装飾品の欠片（7段階）",
    "material-078": "物理武器の欠片（8段階）",
    "material-079": "魔法武器の欠片（8段階）",
    "material-080": "鎧の欠片（8段階）",
    "material-081": "帽子の欠片（8段階）",
    "material-082": "靴の欠片（8段階）",
    "material-083": "きらめく装飾品の欠片（8段階）",
    "material-084": "鮮やかな装飾品の欠片（8段階）",
    "material-085": "物理武器の欠片（9段階）",
    "material-086": "魔法武器の欠片（9段階）",
    "material-087": "鎧の欠片（9段階）",
    "material-088": "帽子の欠片（9段階）",
    "material-089": "靴の欠片（9段階）",
    "material-090": "きらめく装飾品の欠片（9段階）",
    "material-091": "鮮やかな装飾品の欠片（9段階）",
  },
  en: {
    "material-001": "Loose-neck T-shirt",
    "material-002": "Elastic Shorts",
    "material-003": "Hard Baguette",
    "material-004": "Old Cape",
    "material-005": "Red Cloth Belt",
    "material-006": "Small Water Gun",
    "material-007": "Plain Loungewear",
    "material-008": "Rushed Pointed Hat",
    "material-009": "Red Pencil",
    "material-010": "Red Skirt",
    "material-011": "Recyclable Paper Bag",
    "material-012": "Toy Knuckle",
    "material-013": "Red Apron",
    "material-014": "Old Glasses",
    "material-015": "Energy Drink",
    "material-016": "Boxing Gloves",
    "material-017": "Small Mask",
    "material-018": "Small Bread Knife",
    "material-019": "Swim Goggles",
    "material-020": "Old Spoon",
    "material-021": "Plain Slippers",
    "material-022": "Stone-throwing Slingshot",
    "material-023": "Old Slippers",
    "material-024": "Broken Umbrella",
    "material-025": "Candy Ring",
    "material-026": "Red Neck Float",
    "material-027": "Fine Thread Ring",
    "material-028": "Old Wristband",
    "material-029": "Fine Thread Bracelet",
    "material-030": "Old Comb",
    "material-031": "Swirl Candy Necklace",
    "material-032": "Old Cup",
    "material-033": "Cooling Neck Cover",
    "material-034": "Old Coin Purse",
    "material-035": "Candy Earrings",
    "material-036": "Physical Weapon Blueprint (Tier 2)",
    "material-037": "Boots Blueprint (Tier 2)",
    "material-038": "Magic Weapon Blueprint (Tier 2)",
    "material-039": "Sparkling Accessory Blueprint (Tier 2)",
    "material-040": "Armor Blueprint (Tier 2)",
    "material-041": "Brilliant Accessory Blueprint (Tier 2)",
    "material-042": "Hat Blueprint (Tier 2)",
    "material-043": "Physical Weapon Blueprint (Tier 3)",
    "material-044": "Magic Weapon Blueprint (Tier 3)",
    "material-045": "Armor Blueprint (Tier 3)",
    "material-046": "Hat Blueprint (Tier 3)",
    "material-047": "Boots Blueprint (Tier 3)",
    "material-048": "Sparkling Accessory Blueprint (Tier 3)",
    "material-049": "Brilliant Accessory Blueprint (Tier 3)",
    "material-050": "Physical Weapon Fragment (Tier 4)",
    "material-051": "Magic Weapon Fragment (Tier 4)",
    "material-052": "Armor Fragment (Tier 4)",
    "material-053": "Hat Fragment (Tier 4)",
    "material-054": "Boots Fragment (Tier 4)",
    "material-055": "Sparkling Accessory Fragment (Tier 4)",
    "material-056": "Brilliant Accessory Fragment (Tier 4)",
    "material-057": "Physical Weapon Blueprint (Tier 5)",
    "material-058": "Brilliant Accessory Blueprint (Tier 5)",
    "material-059": "Magic Weapon Blueprint (Tier 5)",
    "material-060": "Armor Blueprint (Tier 5)",
    "material-061": "Hat Blueprint (Tier 5)",
    "material-062": "Boots Blueprint (Tier 5)",
    "material-063": "Sparkling Accessory Blueprint (Tier 5)",
    "material-064": "Physical Weapon Blueprint (Tier 6)",
    "material-065": "Brilliant Accessory Fragment Blueprint (Tier 6)",
    "material-066": "Magic Weapon Blueprint (Tier 6)",
    "material-067": "Armor Blueprint (Tier 6)",
    "material-068": "Hat Blueprint (Tier 6)",
    "material-069": "Boots Blueprint (Tier 6)",
    "material-070": "Sparkling Accessory Fragment Blueprint (Tier 6)",
    "material-071": "Physical Weapon Fragment (Tier 7)",
    "material-072": "Magic Weapon Fragment (Tier 7)",
    "material-073": "Armor Fragment (Tier 7)",
    "material-074": "Hat Fragment (Tier 7)",
    "material-075": "Boots Fragment (Tier 7)",
    "material-076": "Sparkling Accessory Fragment (Tier 7)",
    "material-077": "Brilliant Accessory Fragment (Tier 7)",
    "material-078": "Physical Weapon Fragment (Tier 8)",
    "material-079": "Magic Weapon Fragment (Tier 8)",
    "material-080": "Armor Fragment (Tier 8)",
    "material-081": "Hat Fragment (Tier 8)",
    "material-082": "Boots Fragment (Tier 8)",
    "material-083": "Sparkling Accessory Fragment (Tier 8)",
    "material-084": "Brilliant Accessory Fragment (Tier 8)",
    "material-085": "Physical Weapon Fragment (Tier 9)",
    "material-086": "Magic Weapon Fragment (Tier 9)",
    "material-087": "Armor Fragment (Tier 9)",
    "material-088": "Hat Fragment (Tier 9)",
    "material-089": "Boots Fragment (Tier 9)",
    "material-090": "Sparkling Accessory Fragment (Tier 9)",
    "material-091": "Brilliant Accessory Fragment (Tier 9)",
  },
};

export function getMaterialName(material: MaterialId, locale: Locale) {
  return materialNames[locale][material] ?? material;
}

export function getMaterialAssetSlug(material: MaterialId) {
  return getMaterialName(material, "en")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
}

export function getMaterialImagePath(material: MaterialId, rank: number) {
  const basePath = import.meta.env.BASE_URL.endsWith("/") ? import.meta.env.BASE_URL : `${import.meta.env.BASE_URL}/`;
  return `${basePath}assets/gears/rank-${rank}/${getMaterialAssetSlug(material)}.webp`;
}
